### ISSUE TITLE
Problema para subir actualización.

### ISSUE THREAD

**Issue by Avdrns** [lbenet/2022-2_TSFC2#11]
Estoy teniendo este problema para actualizar la tarea. Ya leí un poco eso de fast-forward pero no puedo resolverlo.

![Sin título](https://user-images.githubusercontent.com/80506868/158871787-3718474b-67b9-4676-80ff-74c94ae4bab7.jpg)

Si tuviera que ver con eso del rebase, también ya lo hice, desde mi rama; después de haber hecho el pull desde main.

**Comment by Julian-RC** [comment]
```git push mifork rama```

No estoy seguro que estes realizando esto, puedes ver que sea ```git push NormbreDeTuFork NombreDeTuRama```? y me dices que sucede

**Comment by Avdrns** [comment]
Me sigue mandando el error. Nota que mi rama ya no sólo dice su nombre, sino MERGING.
![Sin título](https://user-images.githubusercontent.com/80506868/158898810-251d2748-46bb-4f3b-96eb-918bf236d213.jpg)

**Comment by lbenet** [comment]
No me queda claro el problema. Para ver qué ocurre, podrías mostrar que sale (en tu terminal) al hacer `git log --oneline`? Me parece que lo que ocurre es que cambiaste localmente algún commit (que ya habías subido a GitHub), y entonces "las historias" ya no corresponden. Por eso quiero ver qué sale con `git log --oneline`. 

Si el problema es ese, la solución puede ser `git push -f My_TSFC2 And_t1`. El `-f` simplemente *fuerza* aceptar el `push` por lo que es de cuidado: puede borrarte el historial, y no es claro que eso es lo que quieres hacer...

**Comment by Avdrns** [comment]
![Sin título](https://user-images.githubusercontent.com/80506868/158909228-017e5c18-f0fd-48df-bb0e-f6d93ae24e80.jpg)

**Comment by lbenet** [comment]
Creo que el problema surgió porque hiciste `git rebase main`. Esto cambió al commit que habías subido antes (que era 1ce5ee0) y ahora es 45328c4 (según tu captura de pantalla), ya que `git rebase` cambia la historia. Entonces, usa `git push -f My_TSFC2 And_t1`. Eso sobreescribirá los commits del pull request.

**Comment by Avdrns** [comment]
Parece ser que ya salió. Cualquier cosa me avisan.
