### ISSUE TITLE
Problema con git

### ISSUE THREAD

**Issue by Avdrns** [lbenet/2022-2_TSFC2#13]
Parece ser que el problemilla que tenía anteriormente con git sigo estando ahí. Iba a actualizar el repositorio para checar la tarea 2 y me sale esto
![help](https://user-images.githubusercontent.com/80506868/160674398-a60d41e5-24a4-475e-ba95-217c83271e2c.jpg)

**Comment by lbenet** [comment]
Primero, aún no he podido subir el .jl del curso ni la Tarea2, cosa que espero hacer durante el día de hoy...

En cuanto a `git`, por el error me da la impresión que hiciste algún cambio en tu archivo `duales.jl`, en el branch en el que estás. Yo pondría `git status` a ver qué sale primero, y dependiendo de eso, vemos qué hacer...

**Comment by Avdrns** [comment]
![help](https://user-images.githubusercontent.com/80506868/160715330-5d43b201-2aff-49f1-8166-1e9baf097def.jpg)

**Comment by lbenet** [comment]
Al parecer sí cambiaste algo en `duales.jl` y después quisiste hacer `git merge`; evita eso :-).

Yo simplemente haría `git merge --abort`, y después `git checkout main` para actualizar respecto al repo del curso.

**Comment by lbenet** [comment]
Creo que el problema fue resuelto... cierro.
