### ISSUE TITLE
De la tarea 2

### ISSUE THREAD

**Issue by SealPi** [lbenet/2022-2_TSFC2#17]
Buenas tardes profesor
respecto a los test y el código, no entiendo de que va "AssertionError", me podría orientar

**Comment by lbenet** [comment]
Los `AssertionError`s aparecen cuando cierta condición no se cumple y utilizas el macro `@assert` para checar la validez de la condición. Un ejemplo muy torpe es el siguiente:
```julia
julia> a = 1
1

julia> @assert iseven(a)
ERROR: AssertionError: iseven(a)
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
```

Julia permite verificar (en los tests) que cierto tipo de errores se disparan en el código; eso es lo que yo hice en los tests. El macro `@assert` es útil cuando quieres que se verifique cierta condición, y si no se verifica te de un error.
