### ISSUE TITLE
Duda Tarea 3

### ISSUE THREAD

**Issue by Avdrns** [lbenet/2022-2_TSFC2#23]
Tengo duda con el caso vectorial.

Después de estar un rato leyendo la redacción de la tarea y cómo es que salió el caso escalar, he ido acomodando las piezas para ver cómo implementar el método. Sin embargo no me queda claro el argumento `du` que aparece desde `coefs_taylor!()`; no veo cuál sería su "análogo" en el caso escalar, ya que no se necesita (y creo no veo su utilidad tampoco en el caso vectorial).

La duda anterior aumentada porque en el momento en que voy obteniendo los coeficientes de Taylor para cada variable dependiente y ver cómo defines el 1er sistema en los tests Luis (las funciones 'f'), no estoy seguro cómo escoger cada función (i.e. la correspondiente a cada ecuación); y más aún, defines el sistema sí con el argumento `dx` que sí se usa en "cada ecuación", pero no lo das.

No veo claro eso aún.

**Comment by lbenet** [comment]
> Después de estar un rato leyendo la redacción de la tarea y cómo es que salió el caso escalar, he ido acomodando las piezas para ver cómo implementar el método. Sin embargo no me queda claro el argumento du que aparece desde coefs_taylor!(); no veo cuál sería su "análogo" en el caso escalar, ya que no se necesita (y creo no veo su utilidad tampoco en el caso vectorial).

En el caso escalar sólo tienes una ecuación, y entonces puedes escribir `du = f(u, p, t)`. Para el caso vectorial, la convención es que las ecuaciones de movimiento son de la forma `f!(du, u, p, t)`, y `du` es modificado por esa función (por eso `!`). Entonces, no hay análogo con el caso vectorial en el sentido que llamar a la función `f!` *cambia* al vector `du`. Esto lo puedes ver en las distintas funciones que hay en los tests, por ejemplo, [aquí](https://github.com/lbenet/2022-2_TSFC2/blob/73ac62f651854610056b9b2dd6d0c19a4681caa5/tareas/tests/integ_taylor.jl#L124).

> La duda anterior aumentada porque en el momento en que voy obteniendo los coeficientes de Taylor para cada variable dependiente y ver cómo defines el 1er sistema en los tests Luis (las funciones 'f'), no estoy seguro cómo escoger cada función (i.e. la correspondiente a cada ecuación)

En cuanto a "cómo escoger cada función", no escoges cada función, si no usas la `du[i]` correspondiente. Entonces, el coeficiente `k+1` de la variable `u[i]` está dado por la relación de recurrencia que usa la `du[i]`. Lo que necesitas es que `u` y `du` sean vectores cuyos elementos son `Taylor1`.

> ... defines el sistema sí con el argumento `dx` que sí se usa en "cada ecuación", pero no lo das.

No entiendo a qué parte te refieres...

**Comment by Avdrns** [comment]
Obtener y actualizar `du` ha sido relativamente fácil como ya había previsto, una vez tuvimos la última discusión.

Pero ahora no me queda claro cómo es que dices que el coeficiente `x_{k}` para cada `u[i]` del sistema es obtenido con la relación de recurrencia de `du[i]`; ¿Cuál relación de recurrencia?. Lo que yo haría es `x_{k}_[i] = du[i].coefs{k-1}/(k-1)` pero recuerdo me dijiste, debido a las particularidades del caso vectorial, no debería meterme con los coeficientes.

**Comment by lbenet** [comment]
> Pero ahora no me queda claro cómo es que dices que el coeficiente `x_{k}` para cada `u[i]` del sistema es obtenido con la relación de recurrencia de `du[i]`; ¿Cuál relación de recurrencia?. Lo que yo haría es `x_{k}_[i] = du[i].coefs{k-1}/(k-1)` ...

La relación que escribes es la correcta, aunque hay que ser cuidadoso con qué representa `k`, aunque está escrita de manera poco inconsistente, así que la reescribo:
<img src=
"https://render.githubusercontent.com/render/math?math=%5Ccolor%7Bblack%7D%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0Au%5E%7B%28i%29%7D_%7B%5Bk%2B1%5D%7D+%3D+%5Cfrac%7Bdu%5E%7B%28i%29%7D_%7B%5Bk%5D%7D%7D%7Bk%2B1%7D%0A%5Cend%7Balign%2A%7D%0A" 
alt="\begin{align*}
u^{(i)}_{[k+1]} = \frac{du^{(i)}_{[k]}}{k+1}
\end{align*}
">
Escrito así, `i` es la componente del vector, y `k` es el orden del último coeficiente que conoces de `u`.

> ... pero recuerdo me dijiste, debido a las particularidades del caso vectorial, no debería meterme con los coeficientes.

Esto lo recordaste justo al revés: mi sugerencia era **no** crear una matriz en términos de coeficientes y componentes, sino más bien, trabajar en términos de las componentes de los vectores y sus coeficientes. De hecho, esto es justo lo que está implícito en la expresión que escribiste!

**Comment by Avdrns** [comment]
No veo porqué pedir así las soluciones, creo complica un poco el cómo las tenemos que ir acomodando una vez las vayamos obteniendo, pero bueno; sólo confirmar que efectivamente así las quieres. Porque por eso no pasa el test.
![help](https://user-images.githubusercontent.com/80506868/170314125-a697d12a-8c42-4a52-81be-1dd76e92fb55.jpg)

**Comment by lbenet** [comment]
No entiendo cuál es tu queja concreta. Si se trata de por qué se escribe la línea como está, en particular el tercer y cuarto argumento, es para que al hacer el broadcasting tanto `x0` como `pp` sean equivalentes a constantes. Si le quitas los paréntesis, verás que te da un error...

**Comment by Avdrns** [comment]
Como sea, ya solucioné eso.

Ya caaasi está, sólo que de nuevo como que me estoy quedando atrasado al momento de avanzar en la obtención de las soluciones, no estoy seguro porqué aún. El código ya está actualizado.
![help](https://user-images.githubusercontent.com/80506868/170318354-db01599f-19e2-4875-a811-384cba102179.jpg)

**Comment by lbenet** [comment]
El problema que reportas está en tu propia implementación: Si te fijas en los resultados que obtienes para `vx`, tienes la condición inicial, un primer valor que parece correcto, y éste último luego *se repite*. Esa observación debería ser suficiente para que cheques de nuevo tu implementación y busque el error...

**Comment by Avdrns** [comment]
Llevo un rato buscándole con `println()`'s, por aquí y por allá, y me parece que lo que no hace es actualizar `xyz` ni `dxyz`. Según yo en la línea señalada eso debería suceder, y como `xyz` y `dxyz` están afuera del `while` ent son vars globales y por ende sí deberían estar cambiando en cada ciclo.
![help](https://user-images.githubusercontent.com/80506868/170355165-eee4e783-a383-4f0e-a848-181eb1e4068b.jpg)

Ent al momento no encuentro el error :/

**Comment by lbenet** [comment]
Checa tu implementación del caso escalar... hay algo en tu implementación del caso vectorial que **no** has hecho, y que **sí** haces en el escalar, y es necesario hacer!
